// AUTO-GENERATED by scripts/fetch-car-photos.mjs — do not edit by hand.
// Photographs come from Wikimedia Commons under the licence recorded on each
// entry. Re-run the script to refresh. Credit is rendered by PhotoCredit.tsx.

import type { CarPhoto } from "./types";

export const carPhotos: Record<string, CarPhoto[]> = {
  "tata-nexon": [
    {
      "src": "/vehicles/tata-nexon-1.jpg",
      "width": 1600,
      "height": 900,
      "title": "2023 Tata Nexon XZA+ front view.jpg",
      "author": "Dairokkan9",
      "licence": "CC BY-SA 4.0",
      "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:2023_Tata_Nexon_XZA%2B_front_view.jpg"
    },
    {
      "src": "/vehicles/tata-nexon-2.jpg",
      "width": 1600,
      "height": 1600,
      "title": "Tata Nexon 2023 Rear View 2.jpg",
      "author": "Harshvyas1001",
      "licence": "CC BY-SA 4.0",
      "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tata_Nexon_2023_Rear_View_2.jpg"
    },
    {
      "src": "/vehicles/tata-nexon-3.jpg",
      "width": 1600,
      "height": 959,
      "title": "Tata Nexon Blue Dual Tone.jpg",
      "author": "Keithkberger",
      "licence": "Public domain",
      "licenceUrl": "",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tata_Nexon_Blue_Dual_Tone.jpg"
    }
  ],
  "maruti-fronx": [
    {
      "src": "/vehicles/maruti-fronx-1.jpg",
      "width": 1600,
      "height": 757,
      "title": "2025 Suzuki Fronx Hybrid front.jpg",
      "author": "LuvsMG481",
      "licence": "CC BY-SA 4.0",
      "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:2025_Suzuki_Fronx_Hybrid_front.jpg"
    },
    {
      "src": "/vehicles/maruti-fronx-2.jpg",
      "width": 1600,
      "height": 900,
      "title": "Suzuki Fronx 1.5 GL 2024.jpg",
      "author": "RL GNZLZ",
      "licence": "CC BY-SA 2.0",
      "licenceUrl": "https://creativecommons.org/licenses/by-sa/2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Suzuki_Fronx_1.5_GL_2024.jpg"
    },
    {
      "src": "/vehicles/maruti-fronx-3.png",
      "width": 1600,
      "height": 960,
      "title": "2023 Suzuki Fronx 1.2 Delta+ (India) front view.png",
      "author": "HARSHIT 0008",
      "licence": "CC BY 3.0",
      "licenceUrl": "https://creativecommons.org/licenses/by/3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:2023_Suzuki_Fronx_1.2_Delta%2B_(India)_front_view.png"
    }
  ],
  "hyundai-creta": [
    {
      "src": "/vehicles/hyundai-creta-1.png",
      "width": 1600,
      "height": 960,
      "title": "2024 Hyundai Creta 1.5 MPi SX(O) (India) front view.png",
      "author": "CARS WORLD Kannada",
      "licence": "CC BY 3.0",
      "licenceUrl": "https://creativecommons.org/licenses/by/3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:2024_Hyundai_Creta_1.5_MPi_SX(O)_(India)_front_view.png"
    },
    {
      "src": "/vehicles/hyundai-creta-2.png",
      "width": 1600,
      "height": 960,
      "title": "2024 Hyundai Creta N Line 1.5 T-GDi (India) front view.png",
      "author": "CARS WORLD Kannada",
      "licence": "CC BY 3.0",
      "licenceUrl": "https://creativecommons.org/licenses/by/3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:2024_Hyundai_Creta_N_Line_1.5_T-GDi_(India)_front_view.png"
    },
    {
      "src": "/vehicles/hyundai-creta-3.jpg",
      "width": 1600,
      "height": 900,
      "title": "Hyundai Creta India.jpg",
      "author": "Nikhilb239",
      "licence": "CC BY-SA 4.0",
      "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hyundai_Creta_India.jpg"
    }
  ],
  "mahindra-xuv-3xo": [
    {
      "src": "/vehicles/mahindra-xuv-3xo-1.jpg",
      "width": 1600,
      "height": 788,
      "title": "2025 Mahindra XUV 3XO AX7L front.jpg",
      "author": "LuvsMG481",
      "licence": "CC BY-SA 4.0",
      "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:2025_Mahindra_XUV_3XO_AX7L_front.jpg"
    },
    {
      "src": "/vehicles/mahindra-xuv-3xo-2.jpg",
      "width": 1600,
      "height": 839,
      "title": "2025 Mahindra XUV 3XO AX7L rear.jpg",
      "author": "LuvsMG481",
      "licence": "CC BY-SA 4.0",
      "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:2025_Mahindra_XUV_3XO_AX7L_rear.jpg"
    },
    {
      "src": "/vehicles/mahindra-xuv-3xo-3.jpg",
      "width": 1600,
      "height": 1221,
      "title": "Mahindra XUV 3XO 2025.jpg",
      "author": "Sreedit",
      "licence": "CC0",
      "licenceUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mahindra_XUV_3XO_2025.jpg"
    }
  ],
  "royal-enfield-classic-350": [
    {
      "src": "/vehicles/royal-enfield-classic-350-1.jpg",
      "width": 1600,
      "height": 1068,
      "title": "Royal Enfield Classic 350 - Gran Via - Madrid 01.jpg",
      "author": "Javier Perez Montes",
      "licence": "CC BY-SA 4.0",
      "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Royal_Enfield_Classic_350_-_Gran_Via_-_Madrid_01.jpg"
    },
    {
      "src": "/vehicles/royal-enfield-classic-350-2.jpg",
      "width": 1600,
      "height": 1200,
      "title": "Royal Enfield Classic Signals 350.jpg",
      "author": "Luca Boldrini",
      "licence": "CC BY 2.0",
      "licenceUrl": "https://creativecommons.org/licenses/by/2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Royal_Enfield_Classic_Signals_350.jpg"
    },
    {
      "src": "/vehicles/royal-enfield-classic-350-3.jpg",
      "width": 1600,
      "height": 899,
      "title": "Royal Enfield Classic 350.jpg",
      "author": "Tirthrajnbarot",
      "licence": "CC BY-SA 3.0",
      "licenceUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Royal_Enfield_Classic_350.jpg"
    }
  ],
  "tvs-iqube": [
    {
      "src": "/vehicles/tvs-iqube-1.jpg",
      "width": 1600,
      "height": 2133,
      "title": "Tvs i qube.jpg",
      "author": "Maneesh Sreekariyam",
      "licence": "CC BY-SA 4.0",
      "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tvs_i_qube.jpg"
    }
  ]
};
